name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install dependencies
      run: go get -v -t -d ./...

    - name: Build-Macos
      run: GOOS=darwin GOARCH=amd64 go build -o ./dist/macos_amd64
    
    - name: Release & Assets
      # You may pin to the exact commit or the version.
      # uses: Hs1r1us/Release-AIO@354b8db50d5b6310b621cb6c5e29d1f8e611aff7
      uses: Hs1r1us/Release-AIO@v1.0
      with:
        # The name of the tag
        tag_name: ${{github.ref}}
        # The name of the release
        release_name: ${{github.ref}}
        # Text describing the contents of the tag
        body: ${{github.ref}}
        asset_files: ./dist/*
