name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install dependencies
      run: go get -v -t -d ./...

    - name: Build-Macos
      run: GOOS=darwin GOARCH=amd64 go build -o ./dist/macos_amd64
    
    - name: Create GitHub release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/macos_amd64
        asset_name: macos_amd64
        asset_content_type: application/gzip
