name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build-Macos
      run: GOOS=darwin GOARCH=amd64 go build -o ./dist/macos_amd64
    
    - name: Create GitHub release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.ReleaseVersion }}
        title: ${{ env.ReleaseVersion }}
        prerelease: false
        files: |
          artifacts/packages/*
